# Generated by Django 5.2.4 on 2025-07-14 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_exercise_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.workout"
            ),
        ),
    ]
