# Generated by Django 5.2.4 on 2025-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_workoutexercise_exercise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
